In [109]:
import cpp
import importlib
import pandas as pd

In [198]:
importlib.reload(cpp)

In [199]:
r=cpp.rules(qpp=True)

In [206]:
case_58 = cpp.account(byear=1968,rules=r)
case_59 = cpp.account(byear=1966,rules=r)

In [207]:
case_58.SetHistoty()
case_59.SetHistoty()

In [208]:
case_58.RunCase(claimage=65,ratio=1.0)
case_59.RunCase(claimage=65,ratio=1.0)

42
[1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2019, 2020, 2020, 2021, 2021, 2022, 2022, 2023]
[25800, 25900, 26500, 27700, 28900, 30500, 32200, 33400, 34400, 34900, 35400, 35800, 36900, 37400, 37600, 38300, 39100, 39900, 40500, 41100, 42100, 43700, 44900, 46300, 47200, 48300, 50100, 51100, 52500, 53600, 54900, 55300, 55900, 57400, 57400, 57400, 57400, 57400, 57400, 57400, 57400, 57400]
agp 68598.50038532427
42
[1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2019, 2020, 2020, 2021, 2021, 2022]
[20800, 23400, 25800, 25900, 26500, 27700, 28900, 30500, 32200, 33400, 34400, 34900, 35400, 35800, 36900, 37400, 37600, 38300, 39100, 39900, 40500, 41100, 42100, 43700, 44900, 46300, 47200, 48300, 50100, 51100, 52500, 53600, 54900, 55300, 55900, 57400, 57400, 57400, 57400, 57400, 57400, 57400]
agp 64660.66583591692

In [195]:
case.ncontrib

42

In [149]:
case.ResetCase()

In [176]:
year =cpp.np.arange(1958,1971)
rage=cpp.np.arange(60,65)
cage=cpp.np.arange(65,70)
tx=cpp.np.arange(.5,1.05,.05)

In [177]:
cpp_out=pd.DataFrame(columns=['byear','retage','claimage','ratio','benefit', 'ncontrib'])
cpp_out

Empty DataFrame
Columns: [byear, retage, claimage, ratio, benefit]
Index: []

In [179]:
count=0
for y in year:
    r=cpp.rules(qpp=True)
    case = cpp.account(byear=y,rules=r)
    for r in rage:
        for c in cage:
            case.RunCase(retage=r,claimage=c,ratio=1.0)
            ben=case.benefit
            cpp_out.at[count,'byear']=y
            cpp_out.at[count,'retage']=r
            cpp_out.at[count,'claimage']=c
            cpp_out.at[count,'ratio']=1
            cpp_out.at[count,'benefit']=ben
            count+=1
            case.ResetCase()

In [180]:
cpp_out

    byear retage claimage ratio  benefit
0    1958     60       65     1  1114.47
1    1958     60       66     1  1213.98
2    1958     60       67     1  1315.22
3    1958     60       68     1  1418.33
4    1958     60       69     1  1523.46
5    1958     61       65     1  1146.32
6    1958     61       66     1  1248.67
7    1958     61       67     1   1352.8
8    1958     61       68     1  1458.85
9    1958     61       69     1  1566.99
10   1958     62       65     1  1178.16
11   1958     62       66     1  1283.35
12   1958     62       67     1  1390.37
13   1958     62       68     1  1499.38
14   1958     62       69     1  1610.52
15   1958     63       65     1     1210
16   1958     63       66     1  1318.04
17   1958     63       67     1  1427.95
18   1958     63       68     1   1539.9
19   1958     63       69     1  1654.05
20   1958     64       65     1  1241.84
21   1958     64       66     1  1352.72
22   1958     64       67     1  1465.53
23   1958     64       68     1  1580.42
24   1958     64       69     1  1697.57
25   1959     60       65     1  1147.91
26   1959     60       66     1   1250.4
27   1959     60       67     1  1354.67
28   1959     60       68     1  1460.88
29   1959     60       69     1  1569.17
..    ...    ...      ...   ...      ...
295  1969     64       65     1     1719
296  1969     64       66     1  1872.49
297  1969     64       67     1  2028.63
298  1969     64       68     1  2187.68
299  1969     64       69     1  2349.84
300  1970     60       65     1  1588.97
301  1970     60       66     1  1730.85
302  1970     60       67     1  1875.19
303  1970     60       68     1   2022.2
304  1970     60       69     1   2172.1
305  1970     61       65     1  1634.37
306  1970     61       66     1   1780.3
307  1970     61       67     1  1928.76
308  1970     61       68     1  2079.98
309  1970     61       69     1  2234.16
310  1970     62       65     1  1679.77
311  1970     62       66     1  1829.75
312  1970     62       67     1  1982.34
313  1970     62       68     1  2137.75
314  1970     62       69     1  2296.22
315  1970     63       65     1  1725.17
316  1970     63       66     1  1879.21
317  1970     63       67     1  2035.92
318  1970     63       68     1  2195.53
319  1970     63       69     1  2358.28
320  1970     64       65     1  1770.57
321  1970     64       66     1  1928.66
322  1970     64       67     1  2089.49
323  1970     64       68     1  2253.31
324  1970     64       69     1  2420.34

[325 rows x 5 columns]